apiVersion: v1
kind: Service
metadata:
  name: {{ include "arigami-tenant.fullname" . }}-headless
  labels:
    {{- include "arigami-tenant.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    {{- include "arigami-tenant.selectorLabels" . | nindent 4 }}
