#!/usr/bin/env bun
// Regenerates skills/render-ui/SKILL.md from the OpenUI library (src/openui/library.jsx).
//   bun web/scripts/openui-prompt.mjs          → writes the file
//   bun web/scripts/openui-prompt.mjs --check  → exit 1 if the file is stale (test/openui-web.test.js)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { openuiPrompt } from '../src/openui/library.jsx';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
export const SKILL_FILE = path.join(ROOT, 'skills/render-ui/SKILL.md');

const HEADER = `---
description: Syntax for the render_ui tool — OpenUI Lang blocks (cards, stats, tables, bar/line charts, buttons, forms) rendered inside the Arigami chat. Load when you want to show the human structured or interactive UI instead of prose, or when render_ui reported a syntax problem. Hebrew: "תציג גרף", "תראה טבלה", "טופס בצ'אט".
---

<!-- GENERATED by web/scripts/openui-prompt.mjs from web/src/openui/library.jsx — do not edit by hand. -->

`;

export function skillText() {
  return HEADER + openuiPrompt();
}

if (import.meta.main) {
  const next = skillText();
  const cur = fs.existsSync(SKILL_FILE) ? fs.readFileSync(SKILL_FILE, 'utf8') : '';
  if (process.argv.includes('--check')) {
    if (cur !== next) { console.error(`stale: ${path.relative(ROOT, SKILL_FILE)} — run bun web/scripts/openui-prompt.mjs`); process.exit(1); }
    console.log('up to date');
  } else {
    fs.mkdirSync(path.dirname(SKILL_FILE), { recursive: true });
    fs.writeFileSync(SKILL_FILE, next);
    console.log(`wrote ${path.relative(ROOT, SKILL_FILE)} (${next.length} chars)`);
  }
}
