import fs from 'node:fs';
import path from 'node:path';
import { randomBytes } from 'node:crypto';
import { broadcast } from './bus.js';
import { cfg, ensureConfigFile } from './lib/config.js';
import { pickSessionAccount } from './accounts.js';

export { cfg, ensureConfigFile };

export const STATE_FILE =
  process.env.ARIGAMI_STATE_FILE || cfg.stateFile;
export const CHAT_DIR =
  process.env.ARIGAMI_CHAT_DIR || cfg.chatDir;

export const nano = (): string =>
  randomBytes(8).toString('base64url').replace(/[-_]/g, () => 'x');

export const untildify = (p: string | null | undefined): string | null | undefined => {
  return p && p.startsWith('~')
    ? path.join(process.env.HOME || '', p.slice(1))
    : p;
};

// ---- Type Definitions ----

// One MCP server's live health verdict. Unlike capabilities.mcpServers (a
// snapshot the init event takes once per proc and never revisits), these are
// re-derived from real signals — the init event, live mcp__* tool results, and
// `claude mcp list` probes under the session's own account — and invalidated
// when the session's account switches (claude.ai connector grants are
// per-account, so a switch silently drops connections the old snapshot still
// reports as "connected").
interface McpServerHealth {
  status: string; // connected | pending | needs-auth | degraded | needs-reconnect | failed | unknown
  statusText?: string;
  at?: number; // when this verdict was recorded
  source?: string; // init | traffic | probe | spawn | stale
}

interface ClaudeState {
  sessionId: string | null;
  state: string;
  permissionMode: string;
  modelChoice?: string | null; // user-picked `claude --model` arg (null = default)
  accountId?: string | null; // account this session runs on (null = active account)
  model?: string; // model id reported by the running session (init event)
  capabilities?: Record<string, unknown>;
  // Live MCP server health map — what the /mcp panel renders (see McpServerHealth).
  mcp?: { servers: Record<string, McpServerHealth>; checkedAt?: number | null } | null;
  // Live context-window usage, derived from each assistant message's token
  // accounting. Drives the "context %" indicator in TermControls/ContextModal.
  usage?: {
    ctxTokens: number;
    ctxWindow: number;
    ctxPct: number;
    breakdown: { cacheRead: number; cacheCreation: number; input: number; output: number };
  } | null;
}

interface ReviewTarget {
  kind?: string;
  path?: string;
  lineLabel?: string;
  featureTitle?: string;
  line?: number;
  key?: string;
}

interface ReviewReply {
  id: string;
  createdAt: string;
  body: string;
  dir?: string | null;
}

interface ReviewComment {
  id: string;
  createdAt: string;
  target?: ReviewTarget;
  body: string;
  dir?: string | null;
  resolved?: boolean;
  suggested?: boolean;
  replies?: ReviewReply[];
}

interface ReviewDraft {
  comments: ReviewComment[];
}

interface TabSession {
  id: string;
  type: 'session';
  title: string;
}

interface TabUrl {
  id: string;
  type: 'url';
  title: string;
  url: string;
  external?: boolean;
  badge?: string;
  color?: string;
  compare?: unknown;
}

interface TabContent {
  id: string;
  type: 'content';
  title: string;
  format: string;
  body: string;
  badge?: string;
}

type Tab = TabSession | TabUrl | TabContent;

interface ChangesExplanation {
  language: string | null;
  generatedAt: string;
  mode: 'pr' | 'uncommitted';
  identity?: string;
  files: unknown[];
  features: unknown[];
}

// A prompt the user queued while the session was busy. Played (sent to Claude)
// manually via ▶, or automatically when the turn ends and autoPlay is on.
export interface PendingPrompt {
  id: string;
  text: string;
  createdAt: string;
}

// A manually-enabled, running status brief for a session (task / progress /
// current state / "what to do now"). Regenerated by a cheap headless run that
// folds the previous text with only the transcript delta since `atSeq`, so it
// stays cheap regardless of conversation length. See claude.js summarizeSession.
export interface StatusSummary {
  text: string;
  tldr?: string; // 2–3 line condensation of `text`, shown as the rail-row tooltip
  lang?: 'auto' | 'en'; // 'auto' = follow the conversation; 'en' = force English
  generatedAt: string;
  autoUpdate: boolean; // refresh after each completed turn
  atSeq: number; // chat seq the summary already accounts for (the fold cursor)
}

interface Session {
  id: string;
  title: string;
  color: string;
  status: string;
  cwd: string;
  archived: boolean;
  createdAt: string;
  updatedAt: string;
  metadata: Record<string, unknown>;
  progress: unknown;
  action: unknown;
  tabs: Tab[];
  activeTabId: string;
  claude: ClaudeState;
  bg: unknown[];
  pendingPrompts?: PendingPrompt[];
  promptAutoPlay?: boolean;
  sortOrder?: number; // manual flat-mode rail order (set by reorderSessions)
  folderId?: string | null; // rail folder membership (null/absent = root)
  changesExplaining?: 'pr' | 'uncommitted' | null;
  changesExplanations?: Record<string, ChangesExplanation>;
  autoReviewing?: 'pr' | 'uncommitted' | null;
  review?: ReviewDraft;
  statusSummary?: StatusSummary | null;
  summarizing?: boolean; // a summary generation run is in flight (transient)
}

// A user-defined rail folder. Membership lives on the session (folderId) so a
// deleted session can't leave a dangling reference; the folder itself is a thin
// record. controllerSessionId present ⇒ "project folder": that session is the
// folder's manager and may task the children (see task_session / DISPATCHER).
export interface Folder {
  id: string;
  name: string;
  collapsed: boolean;
  sortOrder?: number; // shares the root ordering axis with free sessions
  controllerSessionId?: string | null;
  createdAt: string;
  updatedAt: string;
}

interface TabNormResult {
  url: string;
  external?: boolean;
  badge?: string;
}

// A deterministic poller a session arms for an external event it's waiting on
// (e.g. its own PR getting reviewed). The scheduler in listeners.ts polls it and
// wakes the session with a thin signal on a match. See arigami_listeners memory.
export interface Listener {
  id: string;
  sessionId: string;
  type: string; // 'github-pr' | 'linear-issue' | 'slack' | 'worker'
  label: string; // human label for the UI chip, e.g. "PR #123"
  params: Record<string, unknown>; // type-specific (owner, repo, number)
  fireOn: string[]; // event kinds that wake the session
  watermark: Record<string, unknown>; // per-stream cursor (advanced after delivery)
  status: 'watching' | 'errored' | 'stopped';
  firedCount: number;
  createdAt: string;
  ttlAt: number; // epoch ms; auto-stop after this
  intervalSec: number;
  nextPollAt: number; // epoch ms; due when <= now
  backoffLevel: number; // transient-error backoff exponent
  authFails: number; // consecutive auth failures
  lastPolledAt?: number;
  lastError?: string | null;
}

// ---- Store ----

const db: {
  colorIndex: number;
  sessions: Map<string, Session>;
  listeners: Map<string, Listener>;
  folders: Map<string, Folder>;
} = { colorIndex: 0, sessions: new Map(), listeners: new Map(), folders: new Map() };

function load(): void {
  try {
    const j = JSON.parse(fs.readFileSync(STATE_FILE, 'utf8')) as {
      colorIndex?: number;
      sessions?: Session[];
      listeners?: Listener[];
      folders?: Folder[];
    };
    db.colorIndex = j.colorIndex || 0;
    for (const f of j.folders || []) db.folders.set(f.id, f);
    for (const s of j.sessions || []) {
      if (s.claude) s.claude.state = 'idle';
      s.bg = [];
      delete (s as any).changesExplaining;
      delete (s as any).autoReviewing;
      delete (s as any).summarizing; // transient run flag never survives a restart
      db.sessions.set(s.id, s);
    }
    // Rehydrate live listeners; drop ones already finished (self-clean). Force a
    // catch-up poll on boot by making them due now — covers events missed while
    // the host was down (queue-until-idle wakes weren't persisted, so unadvanced
    // watermarks re-detect them).
    for (const l of j.listeners || []) {
      if (l.status === 'stopped') continue;
      if (db.sessions.has(l.sessionId)) {
        l.nextPollAt = 0;
        l.backoffLevel = l.status === 'errored' ? l.backoffLevel : 0;
        db.listeners.set(l.id, l);
      }
    }
  } catch {}
}
load();

let saveTimer: NodeJS.Timeout | null = null;

function persist(): void {
  if (saveTimer) clearTimeout(saveTimer);
  saveTimer = setTimeout(flushState, 500);
}

export function flushState(): void {
  if (saveTimer) clearTimeout(saveTimer);
  saveTimer = null;
  try {
    fs.mkdirSync(path.dirname(STATE_FILE), { recursive: true });
    fs.writeFileSync(
      STATE_FILE,
      JSON.stringify(
        {
          colorIndex: db.colorIndex,
          sessions: [...db.sessions.values()],
          listeners: [...db.listeners.values()],
          folders: [...db.folders.values()],
        },
        null,
        2
      )
    );
  } catch (e) {
    const error = e instanceof Error ? e : new Error(String(e));
    console.error('[state] persist failed:', error.message);
  }
}

// ---- Reads ----

export function listSessions({
  archived = false,
}: { archived?: boolean } = {}): Session[] {
  const all = [...db.sessions.values()];
  return archived ? all : all.filter((s) => !s.archived);
}

export function getSession(id: string): Session | null {
  return db.sessions.get(id) || null;
}

// ---- Mutations ----

function touch(s: Session): void {
  s.updatedAt = new Date().toISOString();
  persist();
}

function nextScratchName(): string {
  let max = 0;
  for (const s of db.sessions.values()) {
    const m = /^scratch-(\d+)$/.exec(s.title || '');
    if (m) max = Math.max(max, Number(m[1]));
  }
  return `scratch-${max + 1}`;
}

export function createSession({
  title,
  cwd,
  permissionMode,
  metadata,
}: {
  title?: string;
  cwd?: string;
  permissionMode?: string;
  metadata?: Record<string, unknown>;
} = {}): Session {
  const now = new Date().toISOString();
  const firstTab: Tab = {
    id: 'tab_' + nano(),
    type: 'session', // the chat/terminal tab — NOT a url tab (empty url loops the proxy bootstrap)
    title: 'Session',
  };
  const session: Session = {
    id: 'sess_' + nano(),
    title: (title || '').trim() || nextScratchName(),
    color: cfg.palette[db.colorIndex++ % cfg.palette.length],
    status: 'In Progress',
    cwd: cwd || cfg.defaultCwd,
    archived: false,
    createdAt: now,
    updatedAt: now,
    metadata:
      metadata && typeof metadata === 'object' ? metadata : {},
    progress: null,
    action: null,
    tabs: [firstTab],
    activeTabId: firstTab.id,
    claude: {
      sessionId: null,
      state: 'idle',
      permissionMode: permissionMode || 'bypassPermissions',
      // Pin the account at creation so the session is explicitly owned and its
      // token is deterministic. Switching the active account later only affects
      // NEW sessions — existing ones keep the account they were created on.
      // Picks the active account, or the next available one if active is
      // rate-limited/quarantined, so a new session doesn't start dead-on-arrival.
      accountId: pickSessionAccount() || null,
      // Seed the session's model from the configured default (cfg.defaultModel);
      // null means "no --model flag", so the CLI picks. The per-session dropdown
      // overrides this later.
      modelChoice: cfg.defaultModel || null,
    },
    bg: [],
  };
  db.sessions.set(session.id, session);
  touch(session);
  broadcast({ type: 'session-created', session });
  return session;
}

const PATCHABLE = new Set([
  'title',
  'color',
  'status',
  'metadata',
  'progress',
  'archived',
  'action',
  'folderId',
]);

export function patchSession(
  id: string,
  patch: Record<string, unknown> = {}
): Session | null {
  const s = getSession(id);
  if (!s) return null;
  for (const [k, v] of Object.entries(patch)) {
    if (!PATCHABLE.has(k)) continue;
    if (k === 'metadata')
      s.metadata = { ...s.metadata, ...(v as Record<string, unknown> || {}) };
    else (s as any)[k] = v;
  }
  // An archived controller can't manage anyone — demote its project folder.
  if (patch.archived === true) releaseControllerOf(id);
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  if ('action' in patch) broadcast({ type: `action:${id}`, action: s.action });
  if ('progress' in patch)
    broadcast({ type: `progress:${id}`, progress: s.progress });
  return s;
}

export function setClaude(
  id: string,
  patch: Partial<ClaudeState> = {}
): Session | null {
  const s = getSession(id);
  if (!s) return null;
  s.claude = { ...s.claude, ...patch };
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return s;
}

// ---- pending prompts --------------------------------------------------------

export function addPendingPrompt(id: string, text: string): PendingPrompt | null {
  const s = getSession(id);
  if (!s) return null;
  const p: PendingPrompt = {
    id: 'pp_' + nano(),
    text: String(text),
    createdAt: new Date().toISOString(),
  };
  s.pendingPrompts = [...(s.pendingPrompts || []), p];
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return p;
}

export function removePendingPrompt(id: string, promptId: string): PendingPrompt | null {
  const s = getSession(id);
  if (!s) return null;
  const list = s.pendingPrompts || [];
  const p = list.find((x) => x.id === promptId) || null;
  if (!p) return null;
  s.pendingPrompts = list.filter((x) => x.id !== promptId);
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return p;
}

export function reorderPendingPrompts(id: string, orderedIds: string[]): Session | null {
  const s = getSession(id);
  if (!s) return null;
  const list = s.pendingPrompts || [];
  const byId = new Map(list.map((p) => [p.id, p]));
  const next: PendingPrompt[] = [];
  for (const pid of orderedIds) {
    const p = byId.get(pid);
    if (p) {
      next.push(p);
      byId.delete(pid);
    }
  }
  next.push(...byId.values()); // anything the client didn't mention keeps its place at the end
  s.pendingPrompts = next;
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return s;
}

export function setPromptAutoPlay(id: string, on: boolean): Session | null {
  const s = getSession(id);
  if (!s) return null;
  s.promptAutoPlay = !!on;
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return s;
}

export function setBg(id: string, bg: unknown[]): Session | null {
  const s = getSession(id);
  if (!s) return null;
  s.bg = bg;
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return s;
}

export function setChangesExplanation(
  id: string,
  mode: string,
  explanation: ChangesExplanation
): Session | null {
  const s = getSession(id);
  if (!s) return null;
  const m = mode === 'pr' ? 'pr' : 'uncommitted';
  if (!s.changesExplanations || typeof s.changesExplanations !== 'object')
    s.changesExplanations = {};
  (s.changesExplanations as Record<string, ChangesExplanation>)[m] =
    explanation;
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return s;
}

export function setChangesExplaining(
  id: string,
  mode?: string
): Session | null {
  const s = getSession(id);
  if (!s) return null;
  s.changesExplaining =
    mode === 'pr' || mode === 'uncommitted' ? (mode as 'pr' | 'uncommitted') : null;
  broadcast({ type: 'session-updated', session: s });
  return s;
}

// ---- status summary ---------------------------------------------------------

// Store a freshly-generated summary (from the headless run). Clears the running
// flag and stamps the fold cursor + timestamp. Persisted (survives restart).
export function setStatusSummary(
  id: string,
  patch: Partial<StatusSummary>
): Session | null {
  const s = getSession(id);
  if (!s) return null;
  const prev = s.statusSummary || ({} as Partial<StatusSummary>);
  s.statusSummary = {
    text: patch.text ?? prev.text ?? '',
    tldr: patch.tldr ?? prev.tldr,
    lang: patch.lang ?? prev.lang ?? 'auto',
    generatedAt: new Date().toISOString(),
    autoUpdate: patch.autoUpdate ?? prev.autoUpdate ?? false,
    atSeq: patch.atSeq ?? prev.atSeq ?? 0,
  };
  s.summarizing = false;
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return s;
}

// Toggle auto-update without regenerating.
export function setSummaryAutoUpdate(id: string, on: boolean): Session | null {
  const s = getSession(id);
  if (!s || !s.statusSummary) return null;
  s.statusSummary = { ...s.statusSummary, autoUpdate: !!on };
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return s;
}

// Set the output language preference ('auto' | 'en'). Caller regenerates.
export function setSummaryLang(id: string, lang: 'auto' | 'en'): Session | null {
  const s = getSession(id);
  if (!s || !s.statusSummary) return null;
  s.statusSummary = { ...s.statusSummary, lang: lang === 'en' ? 'en' : 'auto' };
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return s;
}

// Turn the feature off for a session.
export function clearStatusSummary(id: string): Session | null {
  const s = getSession(id);
  if (!s) return null;
  s.statusSummary = null;
  s.summarizing = false;
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return s;
}

// Transient "generating…" flag — broadcast only, never persisted.
export function setSummarizing(id: string, on: boolean): Session | null {
  const s = getSession(id);
  if (!s) return null;
  s.summarizing = !!on;
  broadcast({ type: 'session-updated', session: s });
  return s;
}

export function addReviewComment(
  id: string,
  comment: Omit<ReviewComment, 'id' | 'createdAt'>
): ReviewComment | null {
  const s = getSession(id);
  if (!s) return null;
  const c: ReviewComment = {
    id: 'cm_' + nano(),
    createdAt: new Date().toISOString(),
    ...comment,
  };
  s.review = {
    comments: [...(s.review?.comments || []), c],
  };
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return c;
}

export function addReviewComments(
  id: string,
  list: Omit<ReviewComment, 'id' | 'createdAt'>[]
): ReviewComment[] | null {
  const s = getSession(id);
  if (!s) return null;
  const add = (Array.isArray(list) ? list : []).map((comment) => ({
    id: 'cm_' + nano(),
    createdAt: new Date().toISOString(),
    ...comment,
  }));
  s.review = {
    comments: [...(s.review?.comments || []), ...add],
  };
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return add;
}

export function removeReviewComment(id: string, cid: string): boolean {
  const s = getSession(id);
  if (!s?.review) return false;
  s.review = {
    comments: s.review.comments.filter((c) => c.id !== cid),
  };
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return true;
}

const findComment = (s: Session | null, cid: string): ReviewComment | null =>
  s?.review?.comments.find((c) => c.id === cid) || null;

export function patchReviewComment(
  id: string,
  cid: string,
  patch: Partial<ReviewComment> = {}
): ReviewComment | null {
  const s = getSession(id);
  const c = findComment(s, cid);
  if (!c) return null;
  if (typeof patch.body === 'string' && patch.body.trim())
    c.body = patch.body;
  if ('resolved' in patch) c.resolved = !!patch.resolved;
  if ('suggested' in patch) c.suggested = !!patch.suggested;
  if (typeof patch.dir === 'string') c.dir = patch.dir;
  touch(s!);
  broadcast({ type: 'session-updated', session: s });
  return c;
}

export function addReviewReply(
  id: string,
  cid: string,
  reply: Omit<ReviewReply, 'id' | 'createdAt'>
): ReviewReply | null {
  const s = getSession(id);
  const c = findComment(s, cid);
  if (!c) return null;
  const r: ReviewReply = {
    id: 're_' + nano(),
    createdAt: new Date().toISOString(),
    ...reply,
  };
  c.replies = [...(c.replies || []), r];
  touch(s!);
  broadcast({ type: 'session-updated', session: s });
  return r;
}

export function patchReviewReply(
  id: string,
  cid: string,
  rid: string,
  patch: Partial<ReviewReply> = {}
): ReviewReply | null {
  const s = getSession(id);
  const r = findComment(s, cid)?.replies?.find((x) => x.id === rid);
  if (!r) return null;
  if (typeof patch.body === 'string' && patch.body.trim())
    r.body = patch.body;
  touch(s!);
  broadcast({ type: 'session-updated', session: s });
  return r;
}

export function removeReviewReply(
  id: string,
  cid: string,
  rid: string
): boolean {
  const s = getSession(id);
  const c = findComment(s, cid);
  if (!c?.replies) return false;
  c.replies = c.replies.filter((x) => x.id !== rid);
  touch(s!);
  broadcast({ type: 'session-updated', session: s });
  return true;
}

export function setAutoReviewing(id: string, mode?: string): Session | null {
  const s = getSession(id);
  if (!s) return null;
  s.autoReviewing =
    mode === 'pr' || mode === 'uncommitted'
      ? (mode as 'pr' | 'uncommitted')
      : null;
  broadcast({ type: 'session-updated', session: s });
  return s;
}

export function clearReview(id: string): Session | null {
  const s = getSession(id);
  if (!s) return null;
  s.review = { comments: [] };
  touch(s);
  broadcast({ type: 'session-updated', session: s });
  return s;
}

// Manual flat-mode rail order: stamp sortOrder by position. Sessions not named
// keep their existing sortOrder (new ones stay undefined → sorted last).
export function reorderSessions(orderedIds: string[]): void {
  orderedIds.forEach((id, i) => {
    const s = db.sessions.get(id);
    if (s) s.sortOrder = i;
  });
  persist();
  for (const id of orderedIds) {
    const s = db.sessions.get(id);
    if (s) broadcast({ type: 'session-updated', session: s });
  }
}

export function deleteSession(id: string): boolean {
  const s = getSession(id);
  if (!s) return false;
  db.sessions.delete(id);
  // Listeners die with their session.
  for (const l of [...db.listeners.values()])
    if (l.sessionId === id) db.listeners.delete(l.id);
  // A dead controller demotes its project folder (children untouched).
  releaseControllerOf(id);
  persist();
  broadcast({ type: 'session-deleted', id });
  return true;
}

// ---- Folders ----------------------------------------------------------------
// Rail folders. Membership = session.folderId; the folder record is thin (see
// the Folder interface). Deleting a folder NEVER deletes sessions here — the
// purge flow (kill children too) lives in the API layer, which owns process
// teardown; state-level delete only ungroups.

export function listFolders(): Folder[] {
  return [...db.folders.values()];
}

export function getFolder(id: string): Folder | null {
  return db.folders.get(id) || null;
}

export function folderChildren(id: string, { archived = false } = {}): Session[] {
  return [...db.sessions.values()]
    .filter((s) => s.folderId === id && (archived || !s.archived))
    .sort((a, b) => (a.sortOrder ?? 1e9) - (b.sortOrder ?? 1e9));
}

export function createFolder({
  name,
  sortOrder,
}: { name?: string; sortOrder?: number } = {}): Folder {
  const now = new Date().toISOString();
  const folder: Folder = {
    id: 'fld_' + nano(),
    name: (name || '').trim() || 'New folder',
    collapsed: false,
    ...(sortOrder != null ? { sortOrder } : {}),
    controllerSessionId: null,
    createdAt: now,
    updatedAt: now,
  };
  db.folders.set(folder.id, folder);
  persist();
  broadcast({ type: 'folder-created', folder });
  return folder;
}

const FOLDER_PATCHABLE = new Set(['name', 'collapsed', 'sortOrder', 'controllerSessionId']);

export function patchFolder(
  id: string,
  patch: Partial<Folder> = {}
): Folder | null {
  const f = db.folders.get(id);
  if (!f) return null;
  for (const [k, v] of Object.entries(patch)) {
    if (FOLDER_PATCHABLE.has(k)) (f as any)[k] = v;
  }
  if (typeof f.name === 'string') f.name = f.name.trim() || f.name;
  f.updatedAt = new Date().toISOString();
  persist();
  broadcast({ type: 'folder-updated', folder: f });
  return f;
}

// Ungroup-and-remove: children return to the root at the folder's position
// (fractional sortOrder slots them between the folder's old neighbours).
export function deleteFolder(id: string): { folder: Folder; children: Session[] } | null {
  const f = db.folders.get(id);
  if (!f) return null;
  const children = folderChildren(id, { archived: true });
  const base = f.sortOrder ?? 1e9;
  children.forEach((s, i) => {
    s.folderId = null;
    s.sortOrder = base + (i + 1) / (children.length + 1);
  });
  db.folders.delete(id);
  persist();
  for (const s of children) broadcast({ type: 'session-updated', session: s });
  broadcast({ type: 'folder-deleted', id });
  return { folder: f, children };
}

// A controller that's gone (deleted/archived) demotes its project folder back
// to a regular one — never leave a folder locked to a ghost session.
export function releaseControllerOf(sessionId: string): void {
  for (const f of db.folders.values()) {
    if (f.controllerSessionId === sessionId) {
      f.controllerSessionId = null;
      f.updatedAt = new Date().toISOString();
      persist();
      broadcast({ type: 'folder-updated', folder: f });
    }
  }
}

// Atomic drop application: membership moves + full root order + per-folder
// internal order, in one call → one consistent broadcast burst (no window
// where a session is in a folder but not yet placed).
export function railReorder({
  root = [],
  folders = {},
  moves = [],
}: {
  root?: { type: 'session' | 'folder'; id: string }[];
  folders?: Record<string, string[]>;
  moves?: { sessionId: string; folderId: string | null }[];
}): void {
  const touched = new Set<string>();
  for (const mv of moves || []) {
    const s = db.sessions.get(String(mv.sessionId));
    if (!s) continue;
    s.folderId = mv.folderId && db.folders.has(mv.folderId) ? mv.folderId : null;
    touched.add(s.id);
  }
  (root || []).forEach((entry, i) => {
    if (entry?.type === 'folder') {
      const f = db.folders.get(String(entry.id));
      if (f) {
        f.sortOrder = i;
        f.updatedAt = new Date().toISOString();
      }
    } else if (entry) {
      const s = db.sessions.get(String(entry.id));
      if (s) {
        s.sortOrder = i;
        touched.add(s.id);
      }
    }
  });
  for (const [fid, ids] of Object.entries(folders || {})) {
    (ids || []).forEach((sid, i) => {
      const s = db.sessions.get(String(sid));
      if (s && s.folderId === fid) {
        s.sortOrder = i;
        touched.add(s.id);
      }
    });
  }
  persist();
  for (const sid of touched) {
    const s = db.sessions.get(sid);
    if (s) broadcast({ type: 'session-updated', session: s });
  }
  broadcast({ type: 'folders-updated', folders: listFolders() });
}

// ---- Listeners ----

export function listListeners(
  { sessionId }: { sessionId?: string } = {}
): Listener[] {
  const all = [...db.listeners.values()];
  return sessionId ? all.filter((l) => l.sessionId === sessionId) : all;
}

export function getListener(id: string): Listener | null {
  return db.listeners.get(id) || null;
}

export function addListener(
  l: Omit<
    Listener,
    'id' | 'createdAt' | 'status' | 'firedCount' | 'backoffLevel' | 'authFails'
  >
): Listener {
  const listener: Listener = {
    id: 'lsn_' + nano(),
    createdAt: new Date().toISOString(),
    status: 'watching',
    firedCount: 0,
    backoffLevel: 0,
    authFails: 0,
    ...l,
  };
  db.listeners.set(listener.id, listener);
  persist();
  broadcast({ type: 'listener-updated', listener });
  return listener;
}

export function patchListener(
  id: string,
  patch: Partial<Listener>
): Listener | null {
  const l = db.listeners.get(id);
  if (!l) return null;
  Object.assign(l, patch);
  persist();
  broadcast({ type: 'listener-updated', listener: l });
  return l;
}

export function removeListener(id: string): boolean {
  const l = db.listeners.get(id);
  if (!l) return false;
  db.listeners.delete(id);
  persist();
  broadcast({ type: 'listener-deleted', id, sessionId: l.sessionId });
  return true;
}

// Stop (but keep) every listener for a session — used when it's archived.
export function stopListenersForSession(sessionId: string): void {
  for (const l of db.listeners.values())
    if (l.sessionId === sessionId && l.status !== 'stopped')
      patchListener(l.id, { status: 'stopped' });
}

// ---- Tabs ----

export function normalizeTabUrl(url: string | null | undefined): TabNormResult {
  const u = String(url || '');
  let m = /linear\.app\/[^/]+\/issue\/([A-Za-z]+-\d+)/.exec(u);
  if (m) return { url: `/__ticket/${m[1].toUpperCase()}` };
  m = /github\.com\/([^/]+)\/([^/]+)\/pull\/(\d+)/.exec(u);
  if (m) return { url: `/__pr/${m[1]}/${m[2]}/${m[3]}`, badge: `#${m[3]}` };
  if (/(^|\.)chromatic\.com|github\.com/.test(u))
    return { url: u, external: true };
  return { url: u };
}

export function addTab(
  id: string,
  {
    type,
    title,
    url,
    format,
    body,
    compare,
    badge,
    color,
  }: {
    type?: string;
    title?: string;
    url?: string;
    format?: string;
    body?: string;
    compare?: unknown;
    badge?: string;
    color?: string;
  } = {}
): Tab | null {
  const s = getSession(id);
  if (!s) return null;
  if (type !== 'url' && type !== 'content')
    throw new Error('tab type must be "url" or "content"');

  const tab: Tab =
    type === 'content'
      ? {
          id: 'tab_' + nano(),
          type: 'content',
          title: title || 'Tab',
          format: format || 'markdown',
          body: body || '',
        }
      : {
          id: 'tab_' + nano(),
          type: 'url',
          title: title || url || 'Tab',
          url: '',
        };

  if (type === 'url') {
    const norm = normalizeTabUrl(url);
    const urlTab = tab as TabUrl;
    urlTab.url = norm.url;
    if (norm.external) urlTab.external = true;
    if (norm.badge && badge === undefined) urlTab.badge = norm.badge;
    if (color) urlTab.color = color;
    if (compare) urlTab.compare = compare;
  }

  if (badge !== undefined) tab.badge = badge;
  s.tabs.push(tab);
  s.activeTabId = tab.id;
  touch(s);
  broadcast({ type: 'tab-created', sessionId: id, tab, session: s });
  return tab;
}

export function patchTab(
  id: string,
  tabId: string,
  patch: Partial<Tab> = {}
): Tab | null {
  const s = getSession(id);
  const tab = s?.tabs.find((t) => t.id === tabId);
  if (!tab) return null;
  for (const k of ['title', 'url', 'body', 'badge', 'color', 'compare', 'format']) {
    if (k in patch) (tab as any)[k] = (patch as any)[k];
  }
  if ('url' in patch) {
    const norm = normalizeTabUrl((patch as any).url);
    (tab as any).url = norm.url;
    if (norm.external) (tab as any).external = true;
    else delete (tab as any).external;
    if (norm.badge && !('badge' in patch) && !(tab as any).badge)
      (tab as any).badge = norm.badge;
  }
  touch(s!);
  broadcast({ type: 'tab-updated', sessionId: id, tab, session: s });
  return tab;
}

export function deleteTab(id: string, tabId: string): boolean {
  const s = getSession(id);
  if (!s) return false;
  const i = s.tabs.findIndex((t) => t.id === tabId);
  if (i < 0) return false;
  if (s.tabs[i].type === 'session')
    throw new Error('cannot close the session tab');
  s.tabs.splice(i, 1);
  if (s.activeTabId === tabId)
    s.activeTabId = s.tabs.length ? s.tabs[Math.max(0, i - 1)].id : '';
  touch(s);
  broadcast({ type: 'tab-deleted', sessionId: id, tabId, session: s });
  return true;
}

export function activateTab(id: string, tabId: string): Session | null {
  const s = getSession(id);
  if (!s || (tabId !== '__changes' && !s.tabs.some((t) => t.id === tabId)))
    return null;
  s.activeTabId = tabId;
  touch(s);
  broadcast({
    type: 'tab-updated',
    sessionId: id,
    tab: s.tabs.find((t) => t.id === tabId),
    session: s,
  });
  return s;
}
