#!/usr/bin/env bun
// POC harness: run `codex exec --json` with arigami's host MCP server wired in,
// under a throwaway CODEX_HOME so we never touch the real one at ~/.codex.
//
// Mirrors mcpConfigFor(s) in server/claude.js:136 — same HOST_SERVERS entry
// (bun mcp/host-mcp.js), translated from the {mcpServers:{...}} JSON Claude
// Code takes inline to the `[mcp_servers.arigami]` TOML table Codex reads from
// $CODEX_HOME/config.toml (snake_case key — Codex silently ignores `mcpServers`).
//
// Usage:
//   bun scripts/codex-poc.ts "<prompt>" [--label NAME] [--tag stream]
//
// Every run captures the full raw JSONL to test/fixtures/codex-stream/<tag>-<ts>.jsonl
// and prints a summary of item.type counts seen.

import { mkdtempSync, writeFileSync, copyFileSync, existsSync, appendFileSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawn } from 'node:child_process';

const REAL_CODEX_HOME = path.join(process.env.HOME || '/home/arigami', '.codex');
const ARIGAMI_ROOT = '/opt/arigami';
const REPO_ROOT = path.resolve(import.meta.dir, '..');
const FIXTURES_DIR = path.join(REPO_ROOT, 'test/fixtures/codex-stream');

function parseArgs(argv) {
  const out = { prompt: null, tag: 'run', toolTimeoutSec: 1800, extraConfig: [] };
  const rest = [];
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--tag') out.tag = argv[++i];
    else if (a === '--tool-timeout-sec') out.toolTimeoutSec = Number(argv[++i]);
    else if (a === '--config') out.extraConfig.push(argv[++i]);
    else rest.push(a);
  }
  out.prompt = rest.join(' ');
  return out;
}

function makeCodexHome() {
  const dir = mkdtempSync(path.join(tmpdir(), 'codex-poc-home-'));
  // auth.json carries the ChatGPT OAuth tokens (auth_mode:"chatgpt") — copy it
  // in so this throwaway CODEX_HOME is already logged in, exactly like the
  // real one. Nothing else from ~/.codex is copied (no session history, no
  // cross-run bleed).
  const authSrc = path.join(REAL_CODEX_HOME, 'auth.json');
  if (existsSync(authSrc)) copyFileSync(authSrc, path.join(dir, 'auth.json'));
  return dir;
}

// Same shape server/claude.js:115 builds for HOST_SERVERS.arigami via
// bunExec('host'): { command: 'bun', args: ['<root>/mcp/host-mcp.js'] }.
function writeConfigToml(codexHome, { toolTimeoutSec, extraConfig }) {
  const hostMcpPath = path.join(ARIGAMI_ROOT, 'mcp', 'host-mcp.js');
  const lines = [
    '# generated by scripts/codex-poc.ts — throwaway, do not edit by hand',
    '',
    '[mcp_servers.arigami]',
    'command = "bun"',
    `args = ["${hostMcpPath}"]`,
    'startup_timeout_sec = 20',
    `tool_timeout_sec = ${toolTimeoutSec}`,
    '',
    '[mcp_servers.arigami.env]',
    `ARIGAMI_SESSION_ID = "${process.env.ARIGAMI_SESSION_ID || ''}"`,
    `ARIGAMI_URL = "${process.env.ARIGAMI_URL || 'http://127.0.0.1:3099'}"`,
    `ARIGAMI_TOKEN = "${process.env.ARIGAMI_TOKEN || ''}"`,
    `ARIGAMI_PUBLIC_PATH = "${process.env.ARIGAMI_PUBLIC_PATH || '/__host/'}"`,
    ...(process.env.ARIGAMI_PUBLIC_URL ? [`ARIGAMI_PUBLIC_URL = "${process.env.ARIGAMI_PUBLIC_URL}"`] : []),
    '',
    ...extraConfig,
  ];
  writeFileSync(path.join(codexHome, 'config.toml'), lines.join('\n') + '\n');
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  if (!args.prompt) {
    console.error('usage: bun scripts/codex-poc.ts "<prompt>" [--tag NAME] [--tool-timeout-sec N]');
    process.exit(1);
  }
  if (!process.env.ARIGAMI_SESSION_ID) {
    console.error('warning: ARIGAMI_SESSION_ID not set in this shell — host tool calls will fail with "no session"');
  }

  const codexHome = makeCodexHome();
  writeConfigToml(codexHome, args);
  console.error(`[codex-poc] CODEX_HOME = ${codexHome}`);

  mkdirSync(FIXTURES_DIR, { recursive: true });
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const fixturePath = path.join(FIXTURES_DIR, `${args.tag}-${ts}.jsonl`);
  const stderrPath = fixturePath.replace(/\.jsonl$/, '.stderr.log');

  const cliArgs = [
    'exec', '--json',
    '--dangerously-bypass-approvals-and-sandbox',
    '--skip-git-repo-check',
    '-C', REPO_ROOT,
    args.prompt,
  ];

  console.error(`[codex-poc] running: codex ${cliArgs.map((a) => (a.includes(' ') ? JSON.stringify(a) : a)).join(' ')}`);
  const startedAt = Date.now();

  const child = spawn('codex', cliArgs, {
    cwd: REPO_ROOT,
    env: { ...process.env, CODEX_HOME: codexHome },
    stdio: ['ignore', 'pipe', 'pipe'],
  });

  const typeCounts = new Map();
  const itemTypeCounts = new Map();
  let firstLineAt = null;
  let lastLineAt = null;

  child.stdout.on('data', (buf) => {
    const now = Date.now();
    if (firstLineAt === null) firstLineAt = now;
    lastLineAt = now;
    appendFileSync(fixturePath, buf);
    for (const line of buf.toString('utf8').split('\n')) {
      const trimmed = line.trim();
      if (!trimmed.startsWith('{')) continue;
      let j;
      try { j = JSON.parse(trimmed); } catch { continue; }
      typeCounts.set(j.type, (typeCounts.get(j.type) || 0) + 1);
      if (j.type === 'item.completed' || j.type === 'item.started') {
        const it = j.item?.type || '?';
        itemTypeCounts.set(it, (itemTypeCounts.get(it) || 0) + 1);
      }
      console.error(`  +${((now - startedAt) / 1000).toFixed(1)}s  ${j.type}${j.item?.type ? ' item.type=' + j.item.type : ''}`);
    }
  });
  child.stderr.on('data', (buf) => appendFileSync(stderrPath, buf));

  const exitCode = await new Promise((resolve) => child.on('close', resolve));
  const endedAt = Date.now();

  console.error('');
  console.error(`[codex-poc] exit code: ${exitCode}`);
  console.error(`[codex-poc] wall time: ${((endedAt - startedAt) / 1000).toFixed(1)}s (first event at +${firstLineAt ? ((firstLineAt - startedAt) / 1000).toFixed(1) : 'n/a'}s, last at +${lastLineAt ? ((lastLineAt - startedAt) / 1000).toFixed(1) : 'n/a'}s)`);
  console.error(`[codex-poc] event type counts: ${JSON.stringify(Object.fromEntries(typeCounts))}`);
  console.error(`[codex-poc] item.type counts: ${JSON.stringify(Object.fromEntries(itemTypeCounts))}`);
  console.error(`[codex-poc] fixture: ${fixturePath}`);
  console.error(`[codex-poc] stderr log: ${stderrPath}`);
  console.error(`[codex-poc] CODEX_HOME: ${codexHome} (left in place for inspection)`);
}

main();
